[features]
seeds = true
skip-lint = false

[programs.localnet]
geiger_entropy = "GeiGR4nd0mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[programs.devnet]
geiger_entropy = "GeiGR4nd0mXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc-testnet.x1.xyz"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
