[daemon]
port = 8746
log_level = "INFO"

[node]
keypair_path = "~/.config/solana/mainnet-deployer.json"
node_name = "Genesis Node"

[entropy]
rolling_pool_size = 10
min_cpm = 5

[serial]
port = "/dev/ttyUSB0"
baud = 115200
poll_interval_ms = 250

[x1]
rpc_url = "https://rpc.mainnet.x1.xyz"
program_id = "BxUNg2yo5371BQMZPkfcxdCptFRDHkhvEXNM1QNPBRYU"
oracle_state = "BygMTZ1oLBD9tDmssnt9LkNT7BEd2PCJBCzurwtMuTqm"
entropy_pool = "GDECYXCXietabJs9Y1baKzD3t4VFBw4eZWPnvYenyi77"
entropy_node = "z4Psp8qVfP4t3jiWHE29rrisTPMC78tu8LmDhRSEL3s"

[tuning]
cycle_sleep_seconds = 15
vdf_iters_low_cpm = 50000
